heat_template_version: 2015-04-30
description: Template to deploy a slice of instances with parameters.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
  subnet_id:
    type: string
    description: Subnet ID for pool.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  num_of_slices:
    type: number
    label: Number of Slices
    description: Number of Slices to be deployed
    constraints:
      - range: {min: 1}
  key:
    type: string
    label: Key pair
    description: Key pair used to access the instance.
  scaling_size:
    type: number
    label: Scaling factor
    description: Maximum value of scaling factor
    default: 1
    constraints:
      - range: {min: 1}
  network_id:
    type: string
    label: Network ID or name
  subnet_id:
    type: string
    label: Subnet ID
resources:
  group-backend:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: 99
      min_size: 1
      resource:
        type: backend.yaml
        properties:
          image_id: { get_param: image_id }
          instance_type: { get_param: instance_type }
          network_id: { get_param: network_id }
          availability_zone: { get_param: availability_zone }
          pool_id: f3be9e32-c854-41a5-8331-9985e923f1f5
          key: { get_param: key }
          subnet_id: { get_param: subnet_id }
  group-api:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: 99
      min_size: 1
      resource:
        type: api.yaml
        properties:
          image_id: { get_param: image_id }
          instance_type: { get_param: instance_type }
          network_id: { get_param: network_id }
          availability_zone: { get_param: availability_zone }
          mysql_server: 192.168.0.164
          pool_id: e1b1173e-1b1d-474b-af88-5653d0365b55
          key: { get_param: key }
          subnet_id: { get_param: subnet_id }
  group-frontend:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: 99
      min_size: 1
      resource:
        type: frontend.yaml
        properties:
          image_id: { get_param: image_id }
          instance_type: { get_param: instance_type }
          network_id: { get_param: network_id }
          availability_zone: { get_param: availability_zone }
          api_server: 192.168.0.165
          pool_id: a57b6bf3-05da-49bf-a67d-257823581b3e
          key: { get_param: key }
          subnet_id: { get_param: subnet_id }
  scaleup_policy_frontend:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-frontend }
      cooldown: 60
      scaling_adjustment: { get_param: scaling_size }
  scaleup_policy_api:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-api }
      cooldown: 60
      scaling_adjustment: { get_param: scaling_size }
  scaleup_policy_backend:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-backend }
      cooldown: 60
      scaling_adjustment: { get_param: scaling_size }
outputs:
  scale_up_url_frontend:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [scaleup_policy_frontend, alarm_url]}
  scale_up_url_api:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [scaleup_policy_api, alarm_url]}
  scale_up_url_backend:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [scaleup_policy_backend, alarm_url]}
